### ISSUE TITLE
[feature] 검색어 리스트 컴포넌트 만들기

### ISSUE THREAD

**Issue by devmagrfs** [wanted-group-4/wanted-preonboarding-movie-info-site#21]
## ISSUE
- Group: `client`
- Type: `feature`
- Detail: Search 페이지에 추천 검색어 리스트 컴포넌트 만들기

## TODO
- [x] SearchList 컴포넌트 만들기
- [x] props에 따라 SearchList 컴포넌트 형식 변화
- [x] 최근 검색어를 localstorage에 최대 10개만 저장하게 구현
- [x] SearchList의 div를 클릭 시 검색창에 value값을 올리기

## Labels
Estimated time: E: `3h`
Group : `client`
